"""Added tasks table

Revision ID: 283910c06805
Revises: bd0f66973edb
Create Date: 2016-05-01 23:45:59.481409

"""

# revision identifiers, used by Alembic.
revision = '283910c06805'
down_revision = 'bd0f66973edb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    ### end Alembic commands ###
