"""New columns

Revision ID: 3d83c3aa59f5
Revises: bdb22d12a468
Create Date: 2016-06-26 21:59:34.216801

"""

# revision identifiers, used by Alembic.
revision = '3d83c3aa59f5'
down_revision = 'bdb22d12a468'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.add_column('tasks', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_timestamp'), 'tasks', ['timestamp'], unique=False)
    op.drop_column('tasks', 'prerequisites')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('prerequisites', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_tasks_timestamp'), table_name='tasks')
    op.drop_column('tasks', 'timestamp')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    ### end Alembic commands ###
